/* Program Data

  in this file you can declare variables to store important data for your program
  the data can only be primitives, objects or arrays
  do not store dom elements in these variables!!!!

  these variables will be imported by your handlers when necessary
    not by your logic
    not by your listeners
*/

export const quizData = [
  {
    id: 'pikachu',
    title: 'Pikachu',
    description: 'Test your knowledge about Pikachu!',
    image: '../public/images/pikachu.jpg',
    currentQuestion: 0,
    points: 0,
    completed: false,
    streak: 0,
    icon: 'electric.svg',
    type: 'electric',
    questions: [
      {
        id: 'pikachu-question-1',
        question: 'What type of Pokémon is Pikachu?',
        options: ['Electric', 'Fire', 'Grass', 'Water'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-2',
        question: 'Who is Pikachu’s trainer in the Pokémon anime?',
        options: ['Ash Ketchum', 'Misty', 'Brock', 'Gary Oak'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-3',
        question: 'What does Pikachu evolve into?',
        options: ['Raichu', 'Pichu', 'Eevee', 'Jolteon'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-4',
        question: 'Which Pokémon is Pikachu’s pre-evolution?',
        options: ['Pichu', 'Eevee', 'Jigglypuff', 'Charmander'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-5',
        question: 'What is Pikachu’s signature move?',
        options: ['Thunderbolt', 'Ember', 'Water Gun', 'Vine Whip'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-6',
        question: 'In which region did Ash first meet Pikachu?',
        options: ['Kanto', 'Johto', 'Hoenn', 'Sinnoh'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-7',
        question: 'What color are Pikachu’s cheeks?',
        options: ['Red', 'Pink', 'Yellow', 'Orange'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-8',
        question: 'Which fruit does Pikachu often like to eat?',
        options: ['Apple', 'Berry', 'Banana', 'Pecha Berry'],
        correctIndex: 3,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-9',
        question: 'What is Pikachu’s Pokédex number?',
        options: ['025', '001', '150', '100'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'pikachu-question-10',
        question: 'What game introduced Pikachu as a starter Pokémon?',
        options: [
          'Pokémon Yellow',
          'Pokémon Red',
          'Pokémon Blue',
          'Pokémon Gold',
        ],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
    ],
  },
  {
    id: 'charizard',
    title: 'Charizard',
    description: 'Prove your knowledge about Charizard!',
    image: '../public/images/Charizard.jpeg',
    currentQuestion: 0,
    points: 0,
    completed: false,
    streak: 0,
    icon: 'fire.svg',
    type: 'fire',
    questions: [
      {
        id: 'charizard-question-1',
        question: 'What type is Charizard?',
        options: ['Fire/Flying', 'Dragon', 'Fire/Ground', 'Fire/Dragon'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-2',
        question: 'What level does Charmeleon evolve into Charizard?',
        options: ['36', '30', '40', '50'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-3',
        question: 'Which generation introduced Charizard?',
        options: ['Gen I', 'Gen II', 'Gen III', 'Gen IV'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-4',
        question: 'Which move is often associated with Charizard?',
        options: ['Flamethrower', 'Hydro Pump', 'Solar Beam', 'Thunder'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-5',
        question: 'Which Mega Evolutions does Charizard have?',
        options: ['X and Y', 'Alpha and Beta', 'Only X', 'Only Y'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-6',
        question: 'What color is Shiny Charizard?',
        options: ['Black', 'Blue', 'Green', 'Gold'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-7',
        question: 'Which starter Pokémon evolves into Charizard?',
        options: ['Charmander', 'Cyndaquil', 'Torchic', 'Tepig'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-8',
        question: 'What is Charizard’s Pokédex number?',
        options: ['006', '150', '025', '004'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-9',
        question: 'Which Gym Leader famously uses Charizard in later games?',
        options: ['Leon', 'Cynthia', 'Brock', 'Misty'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'charizard-question-10',
        question: 'In which region did Ash’s Charizard stay to train?',
        options: ['Johto', 'Charicific Valley', 'Hoenn', 'Sinnoh'],
        correctIndex: 1,
        userAnswer: null,
        skipped: false,
      },
    ],
  },
  {
    id: 'bulbasaur',
    title: 'Bulbasaur',
    description: 'Can you answer all about Bulbasaur?',
    image: '../public/images/bulbazaur.jpg',
    currentQuestion: 0,
    points: 0,
    completed: false,
    streak: 0,
    icon: 'water.svg',
    type: 'water',
    questions: [
      {
        id: 'bulbasaur-question-1',
        question: 'What is Bulbasaur’s type?',
        options: ['Grass/Poison', 'Grass', 'Poison', 'Bug'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-2',
        question: 'What number is Bulbasaur in the Pokédex?',
        options: ['001', '025', '004', '007'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-3',
        question: 'At what level does Bulbasaur evolve into Ivysaur?',
        options: ['16', '20', '18', '12'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-4',
        question: 'What plant grows on Bulbasaur’s back?',
        options: ['Bulb', 'Flower', 'Leaf', 'Tree'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-5',
        question: 'Which starter trio was Bulbasaur part of?',
        options: ['Kanto', 'Johto', 'Hoenn', 'Sinnoh'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-6',
        question: 'Which move is iconic for Bulbasaur?',
        options: ['Vine Whip', 'Tackle', 'Bubble', 'Scratch'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-7',
        question: 'What does Bulbasaur evolve into?',
        options: ['Ivysaur', 'Venusaur', 'Charmander', 'Oddish'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-8',
        question: 'What color is Bulbasaur?',
        options: ['Blue-green', 'Yellow', 'Brown', 'Orange'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-9',
        question: 'Who was the first trainer to catch Bulbasaur in the anime?',
        options: ['Ash', 'Misty', 'Brock', 'Gary'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'bulbasaur-question-10',
        question: 'What is Bulbasaur known as?',
        options: [
          'Seed Pokémon',
          'Bulb Pokémon',
          'Leaf Pokémon',
          'Plant Pokémon',
        ],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
    ],
  },
  {
    id: 'squirtle',
    title: 'Squirtle',
    description: 'Show what you know about Squirtle!',
    image: '../public/images/Squirtle.jpeg',
    currentQuestion: 0,
    points: 0,
    completed: false,
    streak: 0,
    icon: 'grass.svg',
    type: 'grass',
    questions: [
      {
        id: 'squirtle-question-1',
        question: 'What type is Squirtle?',
        options: ['Water', 'Fire', 'Grass', 'Rock'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-2',
        question: 'What is Squirtle’s Pokédex number?',
        options: ['007', '025', '001', '004'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-3',
        question: 'At what level does Squirtle evolve into Wartortle?',
        options: ['16', '20', '18', '25'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-4',
        question: 'What is Squirtle’s signature move?',
        options: ['Water Gun', 'Bubble', 'Surf', 'Hydro Pump'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-5',
        question: 'Which starter trio is Squirtle from?',
        options: ['Kanto', 'Johto', 'Hoenn', 'Sinnoh'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-6',
        question: 'What color is Shiny Squirtle?',
        options: ['Green', 'Light Blue', 'Purple', 'Black'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-7',
        question: 'What gang did Squirtle lead in the anime?',
        options: ['Squirtle Squad', 'Water Force', 'Blue Gang', 'Hydro Team'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-8',
        question: 'Which shell feature makes Squirtle unique?',
        options: [
          'Curved shell for speed',
          'Spikes',
          'Transparent shell',
          'Golden shell',
        ],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-9',
        question: 'Who gave Squirtle sunglasses in the anime?',
        options: ['Himself', 'Ash', 'Misty', 'Brock'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'squirtle-question-10',
        question: 'What is Squirtle’s final evolution?',
        options: ['Blastoise', 'Wartortle', 'Gyarados', 'Lapras'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
    ],
  },
  {
    id: 'jigglypuff',
    title: 'Jigglypuff',
    description: 'Fun quiz about the singing Pokémon Jigglypuff!',
    image: '../public/images/Jigglypuf.jpeg',
    currentQuestion: 0,
    points: 0,
    completed: false,
    streak: 0,
    icon: 'normal.svg',
    type: 'normal',
    questions: [
      {
        id: 'jigglypuff-question-1',
        question: 'What type is Jigglypuff?',
        options: ['Normal/Fairy', 'Fairy', 'Normal', 'Psychic'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-2',
        question: 'What happens when Jigglypuff sings?',
        options: [
          'Everyone falls asleep',
          'Everyone dances',
          'Everyone laughs',
          'Everyone fights',
        ],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-3',
        question: 'What does Jigglypuff use to draw on people who fall asleep?',
        options: ['Marker', 'Stick', 'Lipstick', 'Paint'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-4',
        question: 'What is Jigglypuff’s Pokédex number?',
        options: ['039', '040', '025', '001'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-5',
        question: 'What move is Jigglypuff famous for?',
        options: ['Sing', 'Pound', 'Double Slap', 'Rest'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-6',
        question: 'What color are Jigglypuff’s eyes?',
        options: ['Blue-green', 'Brown', 'Black', 'Red'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-7',
        question: 'What is Jigglypuff’s evolution?',
        options: ['Wigglytuff', 'Clefairy', 'Chansey', 'Igglybuff'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-8',
        question: 'In which region is Jigglypuff first found?',
        options: ['Kanto', 'Johto', 'Hoenn', 'Sinnoh'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-9',
        question: 'Which Smash Bros. game features Jigglypuff as a fighter?',
        options: ['All of them', 'Only Melee', 'Only Ultimate', 'Only 64'],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
      {
        id: 'jigglypuff-question-10',
        question: 'What is Jigglypuff known as in the Pokédex?',
        options: [
          'Balloon Pokémon',
          'Singer Pokémon',
          'Puff Pokémon',
          'Round Pokémon',
        ],
        correctIndex: 0,
        userAnswer: null,
        skipped: false,
      },
    ],
  },
];

export const categories = quizData.map((category) => ({
  id: category.id,
  title: category.title,
  icon: category.icon,
  type: category.type,
}));
